rawdir:
    test/test_data/TEST40
SUP_SAMPLES:
    TEST40
gz:
    True
genome:
    test/test_ref/test_ref.fasta  
backbone_fa:
    data/backbones/BB24.fa
min_insert_length:
    0
max_insert_length:
    300000
3_prime:
     data/seg/3_prime_BB24.fa
5_prime:
     data/seg/5_prime_BB24.fa
mail:
    False
sing:
    False
